pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: GoTool@0
  inputs:
    version: '1.13.10'

- script: |
    set -euo pipefail
    go version
    go get sigs.k8s.io/kind@v0.6.0
    make bootstrap fetch-schemas build lint coverage
    GOOS=windows make build
    GOOS=darwin make build 
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Get dependencies, build, test'

- task: PublishTestResults@2
  inputs:
    testRunner: JUnit
    testResultsFiles: $(System.DefaultWorkingDirectory)/**/report.xml
    failTaskOnFailedTests: true
  condition: always()

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura 
    summaryFileLocation: $(System.DefaultWorkingDirectory)/**/coverage.xml
  condition: always()
